### ISSUE TITLE
The device is disabled by Config entry.

### ISSUE THREAD

**Issue by Fertigmensch666** [Mas2112/solarwatt-energymanager-homeassistant#10]
Hi,

after updating Home Assistant yesterday the integration stopped working. These entires were made in the log.

> 2022-11-12 13:31:07.857 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry EnergyManager ERC04-100002282 for solarwatt_energymanager
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/solarwatt_energymanager/__init__.py", line 19, in async_setup_entry
>     poll_interval = int(entry.data[POLL_INTERVAL])

Since I couldnt help myself otherwise I just tried to disable and add the integration again, which kind of worked. However, since then it says "The device is disabled by Config entry." in the integration settings and no data is shown. Log is showing this:

>2022-11-13 10:08:24.720 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):

>   File "/usr/local/lib/python3.10/site-packages/solarwatt_energymanager/energy_manager.py", line 23, in test_connection
>     json_data = await self.query_json_data()
>   File "/usr/local/lib/python3.10/site-packages/solarwatt_energymanager/energy_manager.py", line 55, in query_json_data
>     async with session.get(self._URL) as response:
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
>     self._resp = await self._coro
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
>     conn = await self._connector.connect(
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
>     proto = await self._create_connection(req, traces, timeout)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
>     _, proto = await self._create_direct_connection(req, traces, timeout)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
>     raise ClientConnectorError(req.connection_key, exc) from exc
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host http:80 ssl:default [Name does not resolve]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/config/custom_components/solarwatt_energymanager/config_flow.py", line 63, in async_step_user
>     serial_number = await validate_host(user_input)
>   File "/config/custom_components/solarwatt_energymanager/config_flow.py", line 32, in validate_host
>     serial_number = await eman.test_connection()
>   File "/usr/local/lib/python3.10/site-packages/solarwatt_energymanager/energy_manager.py", line 25, in test_connection
>     raise CannotConnect
> solarwatt_energymanager.energy_manager.CannotConnect
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
>     resp = await request_handler(request)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
>     resp = await handler(request)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
>     result = await result
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
>     return await super().post(request, flow_id)
>   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
>     result = await method(view, request, data, *args, **kwargs)
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
>     result = await self._flow_mgr.async_configure(flow_id, data)
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
>     result = await self._async_handle_step(
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
>     result: FlowResult = await getattr(flow, method)(user_input)
>   File "/config/custom_components/solarwatt_energymanager/config_flow.py", line 64, in async_step_user
>     except em.CannotConnect:
> AttributeError: module 'solarwatt_energymanager' has no attribute 'CannotConnect'

Nothing really changed (except the HA update). Any help is appreciated!

**Comment by Mas2112** [comment]
Can you try removing the energy manager device and installing it again? I made the polling interval configurable and it looks like it can't find that configuration

**Comment by Fertigmensch666** [comment]
Ok now I feel really stupid. This is basically what I already did, but now it worked. Thank you very much! Have a nice weekend
