### ISSUE TITLE
Issue after update

### ISSUE THREAD

**Issue by Makana80** [Mas2112/solarwatt-energymanager-homeassistant#11]
Hi after Updaet to 0.5.0 i get the following error and no Sensors are loaded.

Logger: homeassistant.config_entries
Source: custom_components/solarwatt_energymanager/__init__.py:19
Integration: SOLARWATT EnergyManager (documentation, issues)
First occurred: 09:17:58 (1 occurrences)
Last logged: 09:17:58

Error setting up entry EnergyManager ERC05-000005115 for solarwatt_energymanager
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/solarwatt_energymanager/__init__.py", line 19, in async_setup_entry
    poll_interval = int(entry.data[POLL_INTERVAL])
KeyError: 'poll_interval'

**Comment by Mas2112** [comment]
Hi, can you try removing the energy manager device and adding it again? The
problem is that in the new version, it's expecting a new parameter.

**Comment by Mas2112** [comment]
Hi. Do you see anything in the home assistant log file?

**Comment by uenglert1** [comment]
Nein, zeigt nichts in der log.file an. Ich möchte mich mit Solarwatt-Energymanager flex verbinden. Ist das möglich? 
PS. Entschuldigung für mein schlechtes Englisch, es ist nur übersetzt

**Comment by Mas2112** [comment]
Energy Manager Flex ist leider nicht von dieser Integration unterstützt.
Auf dem Flex ist ein komplett anderes Betriebssystem.
