### ISSUE TITLE
S0 Energy Meter connected to SolarWatt EnergyManager

### ISSUE THREAD

**Issue by MasterAndi** [Mas2112/solarwatt-energymanager-homeassistant#12]
Hi,

the SolarWatt Energy Manager has 2 Ports for a S0 Energy Meter.
I have connected a S0 Energy Meter to the first Port to get the consumption of a heatpump.

Can you add the Values for this device ?

Needed DataFields should be:
PowerIn
WorkIn

And for Users Measure in both directions:
PowerOut
WorkOut

(ioBroker fetches the complete data from the energymanager and all connected devices like inverter or ev-station.)
Thank You
Andreas

**Comment by Mas2112** [comment]
Can you send me a sample of the JSON data?

**Comment by MasterAndi** [comment]
Attached the json export from /rest/kiwigrid/wizard/devices.
You find the s0counter and also other devices like ev-station or a plug.

[devices.zip](https://github.com/Mas2112/solarwatt-energymanager-homeassistant/files/10796825/devices.zip)

**Comment by Mas2112** [comment]
Do you have any idea what units the power and work values are? W and Wh?

**Comment by Mas2112** [comment]
I have created a beta release 0.6.0. Can you please try it out and let me know if you're getting the data you need?

**Comment by MasterAndi** [comment]
The units are alway W and Wh on the energy manager.

With the beta release I get the values vor the ev stations and the s0 counter, but it is not possible to differentiate between the devices, same names of the entities are counted up.
<img width="910" alt="Sample Names" src="https://user-images.githubusercontent.com/84271286/222948668-8c394c2d-241a-4761-836c-91ca516faf8b.png">

Is it possible to change the names to sensor.energymanager_devicename_... ?

**Comment by Mas2112** [comment]
I updated release 0.6.1 so that the device name is contained in the entity ID. Can you tell me what the entity ID of your S0 Counter shows? I would like to know how it handles Umlauts.

**Comment by MasterAndi** [comment]
That looks great !

wärmepumpe is used as warmepumpe in the entity name. The Friendly Name has the Umlaut.
<img width="961" alt="Warmepumpe" src="https://user-images.githubusercontent.com/84271286/222965878-2a9eb016-fda3-440b-bccf-faf18212dd99.png">

Just one thing for the EV ans S0 Counter, the units for the work entities are kWh but the value is in Wh.
<img width="1049" alt="WorkEV" src="https://user-images.githubusercontent.com/84271286/222966343-3edad711-c564-4fe5-b565-ee71eb93e8c2.png">

The values for the work of the Photovoltaik are correctly shown in kWh.
<img width="1049" alt="WorkPV" src="https://user-images.githubusercontent.com/84271286/222966350-1c559865-b34c-4534-914d-deafb41b9654.png">

**Comment by Mas2112** [comment]
Good to see that Home Assistant handles the Umlauts correctly.

I forgot the conversion. I updated the 0.6.1 version again. Can you please update again?

**Comment by MasterAndi** [comment]
Values and units match now !
Great Job ! Thanks !
