### ISSUE TITLE
call of "async_setup_platforms"

### ISSUE THREAD

**Issue by bochede** [Mas2112/solarwatt-energymanager-homeassistant#13]
hi, first I want to thank you for your good integration.
actually there seems to be a upcoming change - will it be relevant and I should not upgrade HA or can I ignore it? 

`WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for solarwatt_energymanager using this method at custom_components/solarwatt_energymanager/__init__.py, line 23: hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

**Comment by Mas2112** [comment]
This should probably be fixed before HA is updated. I'll try to get it fixed ASAP

**Comment by Mas2112** [comment]
I have create 0.7.0, which is compatible with 2023.3
