### ISSUE TITLE
SOLARWATT Manager Flex Home Assistant

### ISSUE THREAD

**Issue by Frank8410** [Mas2112/solarwatt-energymanager-homeassistant#16]
Hello. I'm currently trying to integrate my Management Flex from Solarwatt into Home Assistant. I did everything as described here. I enter the IP address of the energy manager, but it always shows me an error. Maybe someone can help me.

**Comment by Frank8410** [comment]
![image](https://github.com/Mas2112/solarwatt-energymanager-homeassistant/assets/152327296/f47ced69-6f20-4366-91f7-4d091ca39029)

**Comment by Frank8410** [comment]
![image](https://github.com/Mas2112/solarwatt-energymanager-homeassistant/assets/152327296/82e9ef06-e6fa-4489-a06a-58c32fc34f90)

**Comment by Mas2112** [comment]
Unfortunately, this integration does not support EnergyManager Flex. It uses a different OS, which has a different interface.
