### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by zobde74** [Mas2112/solarwatt-energymanager-homeassistant#2]
Hi,
I am working since hours on the isntallation of the integration but it I am not able to have it working.
I can find it on '/config/custom_components/solarwatt_energymanager' but I can not found it on Configuration -> Integrations

I am using a RP4 with Home Assistant 2022.3.5 
Home Assistant OS
Any idea on what can be wrong?

Thanks in advance
ZobDe

**Comment by Mas2112** [comment]
Hi,

What version are you using and how did you install it? The latest is 0.3.2.
I installed the component using HACS.

Mas

**Comment by zobde74** [comment]
Hi Mas,
I started using the last available 0.3.2 but I also tested some previous versions but the result is the same.
I am installing it via HACS following the instructions.

I can see it installed on '/config/custom_components/solarwatt_energymanager' but I can not found it on Configuration -> Integrations so not able to use it.

Also on HACS after the installation I can not see it but if I install it again it show it is already installed.
I also tried to remove it and start from the beginning. I rebooted many times HA. I also rebooted completely the Raspberry as test

Thanks
ZobDe

**Comment by Mas2112** [comment]
Hi ZobDe,

have you tried adding the device by using the "+ADD INTEGRATION" button? It
should show up in the list.
[image: image.png]
Best regards,

Mas

**Comment by zobde74** [comment]
Hi Mas, sure , I did it.
I just deleted all and started again from the beginning.
I can find following logs on HA

***********************************************
This error is coming from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:597
Integration: HACS (documentation, issues)
First occurred: 21:19:51 (4 occurrences)
Last logged: 21:19:51

A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/Mas2112/solarwatt-energymanager-homeassistant/0.3.2/custom_components/solarwatt_energymanager/strings.json, check the network on the host running Home Assistant
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/Mas2112/solarwatt-energymanager-homeassistant/0.3.2/custom_components/solarwatt_energymanager/manifest.json, check the network on the host running Home Assistant
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/Mas2112/solarwatt-energymanager-homeassistant/0.3.2/custom_components/solarwatt_energymanager/energy_manager.py, check the network on the host running Home Assistant
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/Mas2112/solarwatt-energymanager-homeassistant/0.3.2/custom_components/solarwatt_energymanager/sensor.py, check the network on the host running Home Assistant

******************************************

If I put the 4 urls on my browser I can download the them, but HA is not able ( as I understand from the logs ).
My PC and HA are on the same network so there are no filters on my ISP

Regards
Denis

**Comment by zobde74** [comment]
Hello Mas,
I get it solved.
I manually uploaded the 4 files showed on the logs. In reality I imported all 4 files but after a reboot file sensor.py was again missing. Re-uploaded it again, reboot and now the integration works.
I provided Energy manager IP and now I have 1 device and 17 entities.

I have 3 myreserve installed ( 36Kwh in total ) with 1 Energy manager. 
The integration show the details like battery state of charge only for 1 myreserve :-(

Kind Regards
Denis

**Comment by Mas2112** [comment]
Hi Denis,

3 myreserve battieries? Cool. I don't have any, so I don't know what the
data looks like. It would be very helpful if you can send me a sample json
file from your energy manager. Then I can add support for multiple
batteries.

Can you send me a sample JSON file?
in your browser, you can browse to the address below, and it will return
json data.
http://<ipaddress>/rest/kiwigrid/wizard/devices

Best regards,

Mas

**Comment by zobde74** [comment]
Hi Mas,
here the json
[devices.zip](https://github.com/Mas2112/solarwatt-energymanager-homeassistant/files/8360217/devices.zip)
Thanks
Denis

**Comment by Mas2112** [comment]
Hi Denis,

thanks. Is it OK if I use your file for my unit tests? I will modify
the data so all the personal data will be fake.

I will need some time to get a version running with multiple batteries.

Best regards,

Mas

**Comment by zobde74** [comment]
Hi Mas,
sure. I didn't realized personal data was included.
May be you can download the file and we delete the link...
Thanks
Denis

**Comment by Mas2112** [comment]
Hi Denis,

I have created release 0.4.3-alpha. Please try it out and see if it works.
I have already tested the power and energy values, which is working for me.
But I can't test the batteries.

Best regards,

Mas

**Comment by zobde74** [comment]
Hi Mas,
I completely removed the addon and I was not able to install if following the instructions. I manually uploaded the files like I did last time it was working.
Integration is installed but not working.
Here the logs:

Logger: homeassistant.components.sensor
Source: custom_components/solarwatt_energymanager/sensor_factory.py:293
Integration: Sensore (documentation, issues)
First occurred: 15:21:02 (2 occurrences)
Last logged: 15:21:31

Error while setting up solarwatt_energymanager platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/solarwatt_energymanager/sensor.py", line 48, in async_setup_entry
    entities = create_sensors(coordinator, em_data)
  File "/config/custom_components/solarwatt_energymanager/sensor_factory.py", line 75, in create_sensors
    create_battery_converter_sensors(
  File "/config/custom_components/solarwatt_energymanager/sensor_factory.py", line 293, in create_battery_converter_sensors
    em.BatteryConverterDevice.TAG_VOLTAGE_BATTERY_CELL_STRING,
AttributeError: type object 'BatteryConverterDevice' has no attribute 'TAG_VOLTAGE_BATTERY_CELL_STRING'

Thanks
Denis

**Comment by Mas2112** [comment]
Hi Denis,

I fixed that bug. Can you try 0.4.4-alpha? My component doesn't rely on the order of the values, so it should be able to handle that change you saw.

Here is an animated gif on how I setup the component via HACS.
![solarwatt-energymanager-hacs-setup](https://user-images.githubusercontent.com/169347/161607519-e73c0636-07bf-4c77-a7e1-81de3a9c9445.gif)

What doesn't work in your case?

Mas

**Comment by zobde74** [comment]
HI Mas,
here the error log duirng the installation. 
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:615
Integration: HACS (documentation, issues)
First occurred: 09:52:06 (8 occurrences)
Last logged: 09:53:26

A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/Mas2112/solarwatt-energymanager-homeassistant/0.3.2/custom_components/solarwatt_energymanager/manifest.json, check the network on the host running Home Assistant. This is not a problem with HACS but how your host communicates with GitHub
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/zachowj/hass-node-red/v1.0.7/custom_components/nodered/const.py, check the network on the host running Home Assistant. This is not a problem with HACS but how your host communicates with GitHub
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/zachowj/hass-node-red/v1.0.7/custom_components/nodered/discovery.py, check the network on the host running Home Assistant. This is not a problem with HACS but how your host communicates with GitHub
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/zachowj/hass-node-red/v1.0.7/custom_components/nodered/sensor.py, check the network on the host running Home Assistant. This is not a problem with HACS but how your host communicates with GitHub
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/zachowj/hass-node-red/v1.0.7/custom_components/nodered/manifest.json, check the network on the host running Home Assistant. This is not a problem with HACS but how your host communicates with GitHub

I can manually import the 5 files and than the integration works.

**Comment by zobde74** [comment]
Here the integration installed. Well done!!!

![image](https://user-images.githubusercontent.com/79097946/161718007-05c2d954-edfb-45fe-9898-8e6c6b46f444.png)
![image](https://user-images.githubusercontent.com/79097946/161718141-f933441e-824d-488a-a9fb-2ffa3c6bd802.png)
![image](https://user-images.githubusercontent.com/79097946/161718215-390ac503-652e-4f62-901b-185393610555.png)
![image](https://user-images.githubusercontent.com/79097946/161718297-17d69b51-4021-4a30-b47a-dcc9b2fc3d01.png)

Just a curiosity. Valure "EnergyManager PowerProduced " is showing the sum of the 3 strings I have. Are also the single value of the strings available or only the sum?
For your info, I have 3 strings from the roof ( 6Kw+6Kw+7Kw). Each of this string is connected to a battery pack. So every battery is connected to a single string. Than 2 batteries are going to a Fronius Inverter 12Kw ( the 2 strings with 6Kw) and the other battery( string 7Kw) is going to another Fronius inverter 7Kw.

Denis

**Comment by Mas2112** [comment]
Hi Denis,

I just realized it's really hard to differentiate which value is for which
battery, and which is from the energy manager. I think I need to improve
that.

I've only parsed out the total in and out data and the battery data.

Perhaps you can get the string data from the fronius integration.

https://www.home-assistant.io/integrations/fronius/

I have a Kostal inverter and pull my string data from there directly.

Best regards,

Mas

**Comment by zobde74** [comment]
Ciao Mas,
I am using Fronius intergation but it is useless as till the batteries are not fully charged to the inverters arrive only what the house is using. When the battery are fully charged than the inverters show what arrive from the roof.

Regards
Denis

**Comment by Mas2112** [comment]
Hi Denis,

It looks like something is blocking HACS from downloading the files from
raw.githubusercontent.com. perhaps a firewall or something?

Best regards,

Mas

**Comment by zobde74** [comment]
Hi Mas,
I started using the last available 0.3.2 but I also tested some previous
versions but the result is the same.
I am installing it via HACS following the instructions.

I can see it installed on '/config/custom_components/solarwatt_energymanager'
but I can not found it on Configuration -> Integrations so not able to use
it.

Also on HACS after the installation I can not see it but if I install it
again it show it is already installed.
I also tried to remove it and start from the beginning. I rebooted many
times HA. I also rebooted completely the Raspberry as test

Thanks
ZobDe

Il giorno mer 16 mar 2022 alle ore 17:45 Mas2112 ***@***.***>
ha scritto:

> Hi,
>
> What version are you using and how did you install it? The latest is 0.3.2.
> I installed the component using HACS.
>
> Mas
>

**Comment by Mas2112** [comment]
Hi ZobDe,

There is a newer pre-release version. Can you try that?

Best regards,

Mas

**Comment by zobde74** [comment]
Hi MAS
it seems to work.
I can see more sensor and they are populated with a value.
Now I need to study and understand what it means the new sensors.

Some suggestions:
- as example, already have a average value for the multiple sensors.
As example, I have 3 batteries and you show 3 sensors, one per battery and
this is OK. But I am also calculating the total battery charge because I
can not put ( and it makes no sense in my opinion ) 3 value on the home
assistant dashboard. The same also for other sensors like WorkProduced.
- Another interesting value can be the 3 values for the incoming energy
from roof but may be this are now included now (EnergyManager WorkACIn?)
 and I didn't realized before.
- Last thing, it is not easy to understand the multiple sensor to what it
is referring. As example, I have 3 EnergyManager WorkACIn and not easy to
link the value to the right section of the system. But here no idea about
the data Solarwatt is passing. I provided a name like Battery 1, Battery 2
etc but no idea how this is reported. It seems this is not included on json
file

Denis

**Comment by Mas2112** [comment]
Hi Denis,

Im glad this is working for you!

It seems you can calculate averages using other features or integrations of
HA. See link below.

https://community.home-assistant.io/t/how-to-create-sensor-that-will-be-a-average-of-other-sensors/167393/11

As for the problem with multiple sensors, I'll have to see what I can do. I
have only one inverter and no battery, so my setup is very simple.

I think you sent me your JSON file already, I'll take a look again...

Mas
