### ISSUE TITLE
Install issue new

### ISSUE THREAD

**Issue by Makana80** [Mas2112/solarwatt-energymanager-homeassistant#5]
hi if i want configure the integratin i get this Erorr.
Logger: homeassistant.setup
Source: setup.py:317
First occurred: 13:46:40 (1 occurrences)
Last logged: 13:46:40

Unable to prepare setup for platform solarwatt_energymanager.sensor: Platform not found (cannot import name 'STATE_CLASS_TOTAL' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).

if i delete  the part in senor.py (STATE_CLASS_TOTAL) it  is working but what are the disadvantage?

**Comment by Mas2112** [comment]
What version of the integration have you tried? Can you try the latest 0.4.4-alpha?

**Comment by Makana80** [comment]
i have installed 0.3.2. ok i will try it in the next days with 0.4.4
