### ISSUE TITLE
Can't install solarwatt-energymanager anymore

### ISSUE THREAD

**Issue by Schnuffel2008** [Mas2112/solarwatt-energymanager-homeassistant#7]
Hi,
first of all I want to thank you for this addon.
I have a problem with the installation. I think I've done everything as told and installed the software with hacs. When I try to configurate it my energy-manager isn't detected. Maybe the input for "host" isn't correct. I used only the ip adress and there is a red messagebox "unknown error occured" that appears 1 second after I press return. Then I've tried http://IP-adress. It took a little bit longer but still the same message box. http://solarwattgw give the same result. The strangest thing is that I've set it up 2 weeks ago and everything worked as it should be. Then I've deleted the integration and now I can't set it up again. I have installed a completly new image of home assistant but I can't get it working again.
Do you have any idea what's my mistake?

**Comment by Mas2112** [comment]
Can you try installing the new 0.5.0-alpha version that's in pre-release?

Also do you see an error in the home assistant log file?

**Comment by Schnuffel2008** [comment]
Thank you for your support.
The problem is solved. It didn't belong to your addon but to my energymanager. After resetting and rebooting everything is fine now and your addon give me all of the information that it should. Now I will try out how I can use this for the energy dashboard of homeassistant.
Thanks a lot
