### ISSUE TITLE
Wrong entity on EnergyManager

### ISSUE THREAD

**Issue by M4ndaL0re** [Mas2112/solarwatt-energymanager-homeassistant#8]
Since new update of HA i only see the wrong sensors (total instead of live data) in the Dashboard

**Comment by Mas2112** [comment]
I just updated my HA and had the same problem.

I just released 0.5.0, which contains more sensors. Can you update the integration? After the update, you need to delete the EnergyManager integration and add it again.

**Comment by M4ndaL0re** [comment]
hi, sorry, wrote via iphone and wasnt able to add the entity.
I like to have the actual produced (same view as in EnergyManager) but im unable to use e.g. sensor.energymanager_powerproduced in the Dashboard of Energy from HA. Im only able to use pther entitys to see the summarization of produced or used power. Same for battery etc.

**Comment by M4ndaL0re** [comment]
This is what i have to select.
For the produced (left side) i figured out that it should be the "power self consumed" Entitiy.


![SolarWatt](https://user-images.githubusercontent.com/114978337/196002459-fb249a97-6ac7-4cdb-bc7e-d849f00b45e3.png)
For the other ones as the Entitys with "Power" instead with "work" as the Work Entitys shows only the summarization
![SolarWatt2](https://user-images.githubusercontent.com/114978337/196002576-54574a59-fcc6-4c79-9f77-7ed94aa3073d.png)

**Comment by Mas2112** [comment]
This is actually normal behavior for the home assistant energy management.

To view real time power usage, I think you have to use a different
visualization.

I use this card: https://github.com/JonahKr/power-distribution-card

Which looks at the power data.

**Comment by M4ndaL0re** [comment]
ok thx.
